<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Google.Protobuf" Version="3.31.1" />
      <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
      <PackageReference Include="Grpc.Net.Client" Version="2.71.0" />
      <PackageReference Include="Grpc.Tools" Version="2.72.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.AspNetCore" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Hosting" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Hosting.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Hosting.Server.Abstractions" Version="2.3.0" />
      <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.0" />
      <PackageReference Include="System.CommandLine" Version="2.0.0-beta6.25358.103" />
    </ItemGroup>

    <ItemGroup>
        <Protobuf Include="Proto\service.proto" GrpcServices="Server" />
    </ItemGroup>


    <ItemGroup>
      <ProjectReference Include="..\Nexus.Library\Nexus.Library.csproj" />
    </ItemGroup>


    <ItemGroup>
      <None Update="appsettings.json">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
