<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.6" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="9.0.6" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0"/>
        <PackageReference Include="NUnit" Version="3.14.0"/>
        <PackageReference Include="NUnit.Analyzers" Version="3.9.0"/>
        <PackageReference Include="NUnit3TestAdapter" Version="4.5.0"/>
    </ItemGroup>

    <ItemGroup>
        <Using Include="NUnit.Framework"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Client\Client.csproj" />
      <ProjectReference Include="..\DaprRapr\DaprRapr.csproj" />
      <ProjectReference Include="..\Nexus.Client\Nexus.Client.csproj" />
      <ProjectReference Include="..\Nexus.Library\Nexus.Library.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="Components\binding_doget.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\binding_dopost.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\schedule.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\publisher_rmq.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\subscriber_rmq.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="BasicComponents\binding_doget.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="BasicComponents\binding_dopost.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="BasicComponents\binding_schedule.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="BasicComponents\schedule.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\publisher_kafka.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="Components\subscriber_kafka.yaml">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
