# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x06\x63\x61ller\"\x9b\x01\n\x0cQueryRequest\x12\x13\n\x0b\x62indingName\x18\x01 \x01(\t\x12\x36\n\textraInfo\x18\x02 \x03(\x0b\x32#.caller.QueryRequest.ExtraInfoEntry\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x1a\x30\n\x0e\x45xtraInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x99\x01\n\rQueryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x37\n\textraInfo\x18\x02 \x03(\x0b\x32$.caller.QueryResponse.ExtraInfoEntry\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\t\x1a\x30\n\x0e\x45xtraInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty2>\n\x06\x43\x61ller\x12\x34\n\x05Query\x12\x14.caller.QueryRequest\x1a\x15.caller.QueryResponseB\r\xaa\x02\nGrpcCallerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\nGrpcCaller'
  _globals['_QUERYREQUEST_EXTRAINFOENTRY']._loaded_options = None
  _globals['_QUERYREQUEST_EXTRAINFOENTRY']._serialized_options = b'8\001'
  _globals['_QUERYRESPONSE_EXTRAINFOENTRY']._loaded_options = None
  _globals['_QUERYRESPONSE_EXTRAINFOENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST']._serialized_start=26
  _globals['_QUERYREQUEST']._serialized_end=181
  _globals['_QUERYREQUEST_EXTRAINFOENTRY']._serialized_start=133
  _globals['_QUERYREQUEST_EXTRAINFOENTRY']._serialized_end=181
  _globals['_QUERYRESPONSE']._serialized_start=184
  _globals['_QUERYRESPONSE']._serialized_end=337
  _globals['_QUERYRESPONSE_EXTRAINFOENTRY']._serialized_start=133
  _globals['_QUERYRESPONSE_EXTRAINFOENTRY']._serialized_end=181
  _globals['_EMPTY']._serialized_start=339
  _globals['_EMPTY']._serialized_end=346
  _globals['_CALLER']._serialized_start=348
  _globals['_CALLER']._serialized_end=410
# @@protoc_insertion_point(module_scope)
